var pData = [
  {
    id: "1",
    name: "Danmachi Season-4 Part2",
    airDate: "2023 January",
    genre: ["Action", "Adventure", "Fantasy"],
    recommendedFor: "To inspire with courage or hope",
    rating: "9.5",
    photo: "AnimePhoto/DanmachiS4.jpg",
    link: "https://t.me/animelampmyanmar/473",
  },
  {
    id: "2",
    name: "Tokyo Revenger Season2",
    airDate: "2023 January",
    genre: ["Action", "Fiction", "Thriller"],
    recommendedFor: "Excitement, Fight Scene",
    rating: "9.2",
    photo: "AnimePhoto/TokyoRevengerS2.jpg",
    link: "https://t.me/+QnZYTPBUorgyZGJl",
  },
  {
    id: "3",
    name: "SPY X Family Part-2",
    airDate: "2022 October",
    genre: ["Action", "Comedy", "Spy"],
    recommendedFor: "Family, Detective",
    rating: "9.5",
    photo: "AnimePhoto/SPYXFamilyP2.jpg",
    link: "https://t.me/+u7GwL8-v-JQwYjdl",
  },
  {
    id: "4",
    name: "Beast Tamer",
    airDate: "2022 October",
    genre: ["Fantasy", "Harem Novel"],
    recommendedFor: "Harem",
    rating: "9.0",
    photo: "AnimePhoto/BeastTamer.png",
    link: "https://t.me/animelampmyanmar/360",
  },
];
